const actionTypes = {
  CATEGORIES: "CATEGORIES",
  PRODUCTS: "PRODUCTS",
  SIGN_UP: "SIGN_UP",
  SIGN_IN: "SIGN_IN",
  LOGOUT: "LOGOUT",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  ADD_TO_WISHLIST: "ADD_TO_WISHLIST",
  REMOVE_FROM_WISHLIST: "REMOVE_FROM_WISHLIST",
};

export default actionTypes;
