import { v4 as uuid } from "uuid";

/**
 * name Database can be added here.
 * You can add names of your wish with different attributes
 * */
// out of stock, new, limited,popular
export const products = [
  {
    _id: "10000",
    brand: "OPPO",
    name: "A53",
    color: "Moonlight Black",
    ram: "4 GB",
    storage: "64 GB",
    rating: "4.5",
    price: "11990",
    category: "phone",
    discount: "10",
    img: "MP000000008815938_97Wx144H_202102180007101",
    stock: 15,
    tag: "new",
  },
  {
    _id: "10001",
    brand: "Google Pixel",
    name: "4A",
    color: "Just Black",
    ram: "6 GB",
    storage: "64 GB",
    rating: "4.5",
    price: "21990",
    category: "phone",
    discount: "15",
    img: "google-pixel-4a",
    stock: 5,
    tag: "new",
  },
  {
    _id: "10002",
    brand: "ASUS",
    name: "ZenFone Max M2 ",
    color: "Blue",
    ram: "3 GB",
    storage: "32 GB",
    rating: "4.3",
    price: "12990",
    category: "phone",
    discount: "10",
    img: "66968561",
    stock: 5,
    tag: "",
  },
  {
    _id: "10003",
    brand: "Realme",
    name: "Narzo 30 5G ",
    color: "Racing Silver",
    ram: "6 GB",
    storage: "128 GB",
    rating: "4.3",
    price: "15990",
    category: "phone",
    discount: "5",
    img: "1623400712862",
    stock: 20,
    tag: "popular",
  },
  {
    _id: "10004",
    brand: "Realme",
    name: "8 Pro ",
    color: "Infinite Black",
    ram: "8 GB",
    storage: "128 GB",
    rating: "4.5",
    price: "16990",
    category: "phone",
    discount: "10",
    img: "8-Pro-Infinite-Black",
    stock: 16,
    tag: "new",
  },
  {
    _id: "10005",
    brand: "Apple",
    name: "iPhone 12",
    color: "Black",
    ram: "4 GB",
    storage: "128 GB",
    rating: "4.6",
    price: "68000",
    category: "phone",
    discount: "5",
    img: "71fVoqRC0wLSX522",
    stock: 0,
    tag: "popular",
  },
  {
    _id: "10006",
    brand: "Apple",
    name: "iPhone 13",
    color: "Red",
    ram: "4 GB",
    storage: "256 GB",
    rating: "4.4",
    price: "89900",
    category: "phone",
    discount: "20",
    img: "iphone-13-red",
    stock: 15,
    tag: "popular",
  },
  {
    _id: "10007",
    brand: "SAMSUNG",
    name: "Galaxy A12",
    color: "Blue",
    ram: "4 GB",
    storage: "64 GB",
    rating: "4.2",
    price: "14999",
    category: "phone",
    discount: "20",
    img: "818Vg6xfy7LSY606",
    stock: 0,
    tag: "popular",
  },
  {
    _id: "10008",
    brand: "SAMSUNG",
    name: "Galaxy F12",
    color: "Sky Blue",
    ram: "4 GB",
    storage: "128 GB",
    rating: "4.2",
    price: "12499",
    category: "phone",
    discount: "10",
    img: "MP000000009260671_437W",
    stock: 15,
    tag: "new",
  },
  {
    _id: "10009",
    brand: "SAMSUNG",
    name: "GALAXY M51",
    color: "Black",
    ram: "6 GB",
    storage: "128 GB",
    rating: "4.3",
    price: "24599",
    category: "phone",
    discount: "10",
    img: "Samsung-Galaxy-M51",
    stock: 5,
    tag: "",
  },
  {
    _id: "10010",
    brand: "Lenovo",
    name: "K8 Plus",
    color: "Venom Black",
    ram: "3 GB",
    storage: "32 GB",
    rating: "4.2",
    price: "11000",
    category: "phone",
    discount: "18",
    img: "Lenovo-k8-plus",
    stock: 15,
    tag: "",
  },
  {
    _id: "10011",
    brand: "Motorola",
    name: "G60",
    color: "Frosted Champagne",
    ram: "6 GB",
    storage: "128 GB",
    rating: "4.4",
    price: "17999",
    category: "phone",
    discount: "10",
    img: "1618902238",
    stock: 5,
    tag: "",
  },
  {
    _id: "10012",
    brand: "POCO",
    name: "X3 Pro",
    color: "Graphite",
    ram: "8 GB",
    storage: "128 GB",
    rating: "4.3",
    price: "20990",
    category: "phone",
    discount: "10",
    img: "1616420587",
    stock: 5,
    tag: "popular",
  },
  {
    _id: "10013",
    brand: "Vivo",
    name: "Y33s",
    color: "Midday Dream",
    ram: "6 GB",
    storage: "64 GB",
    rating: "4.4",
    price: "37990",
    category: "phone",
    discount: "19",
    img: "84c215af-cf3e-44a7-9b66-560e0c294eda",
    stock: 10,
    tag: "popular",
  },
  {
    _id: "10014",
    brand: "Xiaomi",
    name: "MI 11X 5G",
    color: "CELESTIAL SILVER",
    ram: "6 GB",
    storage: "128 GB",
    rating: "4.4",
    price: "26295",
    category: "phone",
    discount: "10",
    img: "81PQCRubagSSL1500",
    stock: 15,
    tag: "new",
  },
  {
    _id: "10884",
    brand: "Xiaomi",
    name: "Redmi Note 9 Pro ",
    color: "Interstellar Black",
    ram: "6 GB",
    storage: "128 GB",
    rating: "3.8",
    price: "17999",
    category: "phone",
    discount: "18",
    img: "A0F36EF9-A32C-FF2F-E2D5-1FE5124589C2",
    stock: 15,
    tag: "popular",
  },
  {
    _id: "20000",
    brand: "Apple",
    name: "MacBook Pro - 8GB",
    typeName: "Ultrabook",
    inches: "13.3",
    screenResolution: "IPS Panel Retina Display 2560x1600",
    cpu: "Intel Core i5 2.3GHz",
    ram: "8GB",
    memory: "128GB SSD",
    gpu: "Intel Iris Plus Graphics 640",
    opSys: "macOS",
    weight: "1.37kg",
    price: "112533.96",
    category: "laptop",
    discount: "10",
    rating: "4",
    img: "mbp-spacegray",
    stock: 15,
    tag: "",
  },
  {
    _id: "20001",
    brand: "Apple",
    name: "Macbook Air",
    typeName: "Ultrabook",
    inches: "13.3",
    screenResolution: "1440x900",
    cpu: "Intel Core i5 1.8GHz",
    ram: "8GB",
    memory: "128GB Flash Storage",
    gpu: "Intel HD Graphics 6000",
    opSys: "macOS",
    weight: "1.34kg",
    price: "75510.96",
    category: "laptop",
    discount: "10",
    rating: "4",
    img: "71k3fJh5EwLACSL1500",
    stock: 15,
    tag: "new",
  },
  {
    _id: "20002",
    brand: "HP",
    name: "250 G6",
    typeName: "Notebook",
    inches: "15.6",
    screenResolution: "Full HD 1920x1080",
    cpu: "Intel Core i5 7200U 2.5GHz",
    ram: "8GB",
    memory: "256GB SSD",
    gpu: "Intel HD Graphics 620",
    opSys: "No OS",
    weight: "1.86kg",
    price: "48300",
    category: "laptop",
    discount: "15",
    rating: "4.5",
    img: "c05476924",
    stock: 15,
    tag: "",
  },
  {
    _id: "20003",
    brand: "Apple",
    name: "MacBook Pro - 16GB",
    typeName: "Ultrabook",
    inches: "15.4",
    screenResolution: "IPS Panel Retina Display 2880x1800",
    cpu: "Intel Core i7 2.7GHz",
    ram: "16GB",
    memory: "512GB SSD",
    gpu: "AMD Radeon Pro 455",
    opSys: "macOS",
    weight: "1.83kg",
    price: "213145.8",
    category: "laptop",
    discount: "8",
    rating: "3",
    img: "mbp-spacegray",
    stock: 15,
    tag: "new",
  },
  {
    _id: "20005",
    brand: "Acer",
    name: "Aspire 3",
    typeName: "Notebook",
    inches: "15.6",
    screenResolution: "1366x768",
    cpu: "AMD A9-Series 9420 3GHz",
    ram: "4GB",
    memory: "500GB HDD",
    gpu: "AMD Radeon R5",
    opSys: "Windows 10",
    weight: "2.1kg",
    price: "33600",
    category: "laptop",
    discount: "15",
    rating: "2",
    img: "610oaBCrXLSL1310",
    stock: 15,
    tag: "",
  },
  {
    _id: "20008",
    brand: "Asus",
    name: "ZenBook UX430UN",
    typeName: "Ultrabook",
    inches: "14",
    screenResolution: "Full HD 1920x1080",
    cpu: "Intel Core i7 8550U 1.8GHz",
    ram: "16GB",
    memory: "512GB SSD",
    gpu: "Nvidia GeForce MX150",
    opSys: "Windows 10",
    weight: "1.3kg",
    price: "125580",
    category: "laptop",
    discount: "20",
    rating: "5",
    img: "asus-zenbook-ux430un",
    stock: 15,
    tag: "popular",
  },
  {
    _id: "20009",
    brand: "Acer",
    name: "Swift 3",
    typeName: "Ultrabook",
    inches: "14",
    screenResolution: "IPS Panel Full HD 1920x1080",
    cpu: "Intel Core i5 8250U 1.6GHz",
    ram: "8GB",
    memory: "256GB SSD",
    gpu: "Intel UHD Graphics 620",
    opSys: "Windows 10",
    weight: "1.6kg",
    price: "64680",
    category: "laptop",
    discount: "30",
    rating: "5",
    img: "71vP01mvupLSL1500",
    stock: 15,
    tag: "",
  },

  {
    _id: "20013",
    brand: "Dell",
    name: "Inspiron 3567",
    typeName: "Notebook",
    inches: "15.6",
    screenResolution: "Full HD 1920x1080",
    cpu: "Intel Core i3 6006U 2GHz",
    ram: "4GB",
    memory: "256GB SSD",
    gpu: "AMD Radeon R5 M430",
    opSys: "Windows 10",
    weight: "2.2kg",
    price: "41907.6",
    category: "laptop",
    discount: "20",
    rating: "2.5",
    img: "products-15-35762",
    stock: 1,
    tag: "",
  },
  {
    _id: "20014",
    brand: "Apple",
    name: "MacBook 12",
    typeName: "Ultrabook",
    inches: "12",
    screenResolution: "IPS Panel Retina Display 2304x1440",
    cpu: "Intel Core M m3 1.2GHz",
    ram: "8GB",
    memory: "256GB SSD",
    gpu: "Intel HD Graphics 615",
    opSys: "macOS",
    weight: "0.92kg",
    price: "106041.6",
    category: "laptop",
    discount: "5",
    rating: "3",
    img: "macbook12",
    stock: 0,
    tag: "",
  },
  {
    _id: "40001",
    brand: "Boult",
    name: "Audio Pro Bass Curve Neckband Bluetooth Headset",
    color: "Blue",
    type: " Black",
    rating: "4",
    num_of_ratings: "333036",
    price: "799",
    category: "earphone",
    img: "61nCtD25VZLSX679",
    stock: 15,
    tag: "",
  },
  {
    _id: "40002",
    brand: "Aroma",
    name: "NB120 Tehalka - 28 Hours Playtime Bluetooth Neckband",
    color: "Black",
    type: " In the Ear",
    rating: "3.9",
    num_of_ratings: "10398",
    price: "379",
    category: "earphone",
    img: "imag6444my9aegkg",
    stock: 15,
    tag: "new",
  },

  {
    _id: "40004",
    brand: "OnePlus",
    name: "Bullets Wireless Z Bass Edition Bluetooth Headset",
    color: "Bold Black",
    type: " In the Ear",
    rating: "4.3",
    num_of_ratings: "437395",
    price: "1999",
    category: "earphone",
    img: "61DKcGr12OL._SL1500_",
    stock: 5,
    tag: "",
  },

  {
    _id: "40006",
    brand: "Oxhox",
    name: "HBS-730 Sports Stereo Headphone Bluetooth Headset",
    color: "Black",
    type: " In the Ear",
    rating: "3.5",
    num_of_ratings: "12909",
    price: "260",
    category: "earphone",
    img: "imafwrggkh8uf8uc",
    stock: 0,
    tag: "",
  },

  {
    _id: "40008",
    brand: "boAt",
    name: "Bassheads 103 Black Wired Headset",
    color: "Black",
    type: " In the Ear",
    rating: "4.2",
    num_of_ratings: "1299042",
    price: "349",
    category: "earphone",
    img: "BOTASSHEADS103BK",
    stock: 15,
    tag: "popular",
  },
  {
    _id: "40009",
    brand: "boAt",
    name: "Rockerz 235v2 with ASAP charging Version 5.0 Bluetooth",
    color: "Black",
    type: " In the Ear",
    rating: "3.4",
    num_of_ratings: "48161",
    price: "999",
    category: "earphone",
    img: "imaftk6us4af7bca",
    stock: 15,
    tag: "new",
  },

  {
    _id: "40846",
    brand: "Obin",
    name: "BB-01 BoomBass Wired Headset",
    color: "Black",
    type: " In the Ear",
    rating: "3.9",
    num_of_ratings: "10398",
    price: "239",
    category: "earphone",
    img: "imag9yy7bzgqcxpn",
    stock: 0,
    tag: "",
  },
  {
    _id: "40847",
    brand: "Apple",
    name: "Watch Series 7 Aluminium Case with Abyss Blue Sport Band - Regular",
    color: "Blue",
    rating: "3.9",
    num_of_ratings: "1098",
    price: "53900",
    category: "watch",
    img: "apple-watch",
    stock: 5,
    tag: "new",
  },
  {
    _id: "40848",
    brand: "Mi",
    name: "Smart Band 5",
    color: "Black",
    rating: "4.3",
    num_of_ratings: "3098",
    price: "2500",
    category: "watch",
    img: "mi-band",
    stock: 5,
    discount: 2,
    tag: "popular",
  },
];
